version: "3.8"

services:
  bot:
    container_name: marvin
    image: ghcr.io/42dotmk/marvin:latest
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./bot.log:/app/bot.log
