version: "3.8"

services:
  bot:
    container_name: marvin-dev
    build:
      context: .
      dockerfile: ./Dockerfile
      target: development
    image: marvin-dev:latest
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    command: ["npm", "run", "dev"]
