version: "3.8"

services:
  bot:
    container_name: marvin
    image: marvin
    build: .
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - database
    volumes:
      - ./bot.log:/app/bot.log
